### ISSUE TITLE
linter doesn't run on travis?

### ISSUE THREAD

**Issue by joeybaker** [joeybaker/remapify#30]
See #11

**Comment by brianmgray** [comment]
Here is the output I get when I run "npm run lint"
````
$ npm run lint

> remapify@1.4.4 lint c:\Users\bgray\workspaces\scratch\remapify
> npm run jshint && npm run jscs


> remapify@1.4.4 jshint c:\Users\bgray\workspaces\scratch\remapify
> jshint --reporter node_modules/jshint-stylish/stylish.js


√ No problems


> remapify@1.4.4 jscs c:\Users\bgray\workspaces\scratch\remapify
> jscs .

TypeError: Cannot read property 'type' of undefined
    at c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\rules\require-multiple-var-decl.js:41:24
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\js-file.js:328:42)
    at Object.consecutive [as _check] (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\rules\require-multiple-var-decl.js:37:10)
    at Object.module.exports.check (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\rules\require-multiple-var-decl.js:119:28)
    at null.<anonymous> (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\string-checker.js:121:22)
    at Array.forEach (native)
    at StringChecker.checkString (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\string-checker.js:119:35)
    at null.<anonymous> (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\checker.js:40:25)
    at Array.0 (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\node_modules\vow\lib\vow.js:699:39)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Users\\bgray\\apps\\ConsolePortable\\util\\nodejs\\\\node.exe" "c:\\Users\\bgray\\apps\\ConsolePortable\\util\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "jscs"
npm ERR! node v0.10.30
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE
npm ERR! remapify@1.4.4 jscs: `jscs .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remapify@1.4.4 jscs script.
npm ERR! This is most likely a problem with the remapify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jscs .
npm ERR! You can get their info via:
npm ERR!     npm owner ls remapify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\bgray\workspaces\scratch\remapify\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\users\\bgray\\apps\\ConsolePortable\\util\\nodejs\\node.exe" "c:\\users\\bgray\\apps\\ConsolePortable\\util\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v0.10.30
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE
npm ERR! remapify@1.4.4 lint: `npm run jshint && npm run jscs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remapify@1.4.4 lint script.
npm ERR! This is most likely a problem with the remapify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run jshint && npm run jscs
npm ERR! You can get their info via:
npm ERR!     npm owner ls remapify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\bgray\workspaces\scratch\remapify\npm-debug.log
````

And here's when I run "npm install"
````
$ npm install
-
> ghooks@0.2.2 install c:\Users\bgray\workspaces\scratch\remapify\node_modules\ghooks
> ./bin/install

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\users\\bgray\\apps\\ConsolePortable\\util\\nodejs\\node.exe" "c:\\users\\bgray\\apps\\ConsolePortable\\util\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.10.30
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE

npm ERR! ghooks@0.2.2 install: `./bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ghooks@0.2.2 install script.
npm ERR! This is most likely a problem with the ghooks package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls ghooks
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\bgray\workspaces\scratch\remapify\npm-debug.log
````

**Comment by joeybaker** [comment]
Looks like this got fixed with a module update.
